version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pipeline_postgres
    restart: always
    environment:
      POSTGRES_USER: hornet
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pipeline_weather
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
